export const SPECIALTIES: any = [
  {
    id: 1,
    specialty: 'Pediatrician',
    image: '/assets/specialties/pexels-victoria-akvarel-1648378.jpg',
  },
  {
    id: 2,
    specialty: 'Physician',
    image: '/assets/specialties/pexels-polina-tankilevitch-3873179.jpg',
  },
  {
    id: 3,
    specialty: 'Gynaecologist',
    image: '/assets/specialties/janko-ferlic-ZNVGL_Pcf74-unsplash.jpg',
  },
  {
    id: 4,
    specialty: 'Dermatologist',
    image: '/assets/specialties/dermatologist.png',
  },
  {
    id: 5,
    specialty: 'Dietitian',
    image: '/assets/specialties/pexels-annushka-ahuja-7991922.jpg',
  },
  {
    id: 6,
    specialty: 'Orthopedician',
    image: '/assets/specialties/Orthopedician.png',
  },
  {
    id: 7,
    specialty: 'Fertility Specialist',
    image: '/assets/specialties/pexels-ngakan-eka-3699327.jpg',
  },
  {
    id: 8,
    specialty: 'Cardiologist',
    image: '/assets/specialties/pexels-karolina-grabowska-4386467.jpg',
  },
  {
    id: 9,
    specialty: 'General Surgeon',
    image: '/assets/specialties/surgeon.png',
  },
  {
    id: 10,
    specialty: 'Gastroenterologist',
    image: '/assets/specialties/Gastroenterologist.png',
  },
  {
    id: 11,
    specialty: 'Pulmonologist',
    image: '/assets/specialties/Pulmonologist.png',
  },
  {
    id: 12,
    specialty: 'Oncologist',
    image: '/assets/specialties/Oncologist.png',
  },
];

export const DOCTORS: any = [
  {
    id: 1,
    name: 'Lena Mueller',
    doctorImage: '/assets/doctors/doctor1.jpg',
    qualifications: 'MD, MSc',
    specialty: 'Pediatrician',
    languages: 'German, English',
    price: '149',
    yearsExperience: '11',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Berlin, Germany',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Charité – Universitätsmedizin Berlin',
    degreeObtained2: 'Master of Science',
    university2: 'Humboldt University of Berlin',
  },
  {
    id: 2,
    name: 'Liam Murphy',
    doctorImage: '/assets/doctors/doctor2.jpg',
    qualifications: 'MD, MSc',
    specialty: 'Pediatrician',
    languages: 'English, German',
    price: '179',
    yearsExperience: '23',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Dublin, Ireland',
    degreeObtained1: 'MB BCh BAO',
    university1: 'University College Dublin',
    degreeObtained2: 'MSc in Child Health and Wellbeing',
    university2: 'Trinity College Dublin',
  },
  {
    id: 3,
    name: 'Emma Nielsen',
    doctorImage: ' /assets/doctors/doctor3.png',
    qualifications: 'MD, MPH',
    specialty: 'Pediatrician',
    languages: 'Danish, English',
    price: '119',
    yearsExperience: '12',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Copenhagen, Denmark',
    degreeObtained1: 'Cand.med.',
    university1: 'University of Copenhagen',
    degreeObtained2: 'MPH in Global Health',
    university2: 'University of Southern Denmark',
  },
  {
    id: 4,
    name: 'Oliver Hansen',
    doctorImage: ' /assets/doctors/doctor4.png',
    qualifications: 'MD, DSc',
    specialty: 'Physician',
    languages: 'English, Dutch',
    price: '129',
    yearsExperience: '20',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Amsterdam, Netherlands',
    degreeObtained1: 'Doctor of Medicine (MD)',
    university1: 'University of Amsterdam',
    degreeObtained2: 'Doctor of Science (DSc)',
    university2: 'Erasmus University Rotterdam',
  },
  {
    id: 5,
    name: 'Hannah Kovalenko',
    qualifications: 'MD, PhD',
    specialty: 'Physician',
    languages: 'Ukrainian, English',
    price: '189',
    yearsExperience: '26',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Kiev, Ukraine',
    degreeObtained1: 'Doctor of Medicine (MD)',
    university1: 'Taras Shevchenko National University of Kyiv',
    degreeObtained2: 'Doctor of Philosophy (PhD)',
    university2: 'National Academy of Sciences of Ukraine',
  },
  {
    id: 33,
    name: 'Anna Novakova',
    qualifications: 'MD, PhD',
    specialty: 'Cardiologist',
    languages: 'Czech, English',
    price: '149',
    yearsExperience: '14',
    hospital: 'Prague General Hospital',
    logoHospital: '/assets/hospitals/praguegeneralhospital.png',
    location: 'Prague, Czech Republic',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Charles University',
    degreeObtained2: 'Master of Science in Cardiology',
    university2: 'Masaryk University',
  },

  {
    id: 7,
    name: 'Alicia Fernandez',
    doctorImage: '/assets/doctors/pexels-antoni-shkraba-6749777-229x310.jpg',
    qualifications: 'MD, MPH',
    specialty: 'Gynaecologist',
    languages: 'Spanish, English',
    price: '99',
    yearsExperience: '11',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Madrid, Spain',
    degreeObtained1: 'Doctor of Medicine (MD)',
    university1: 'Complutense University of Madrid',
    degreeObtained2: 'Master of Public Health (MPH)',
    university2: 'University of Barcelona',
  },
  {
    id: 8,
    name: 'Lucas Mikkelsen',
    qualifications: 'MD, PhD',
    specialty: 'Gynaecologist',
    languages: 'Danish, Swedish',
    price: '169',
    yearsExperience: '21',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Stockholm, Sweden',
    degreeObtained1: 'Bachelor of Medicine and Surgery',
    university1: 'Karolinska Institute',
    degreeObtained2: 'Doctor of Philosophy in Medicine',
    university2: 'Uppsala University',
  },

  {
    id: 9,
    name: 'Valentina Rossi',
    qualifications: 'MD, PhD',
    specialty: 'Cardiologist',
    languages: 'Italian, English',
    price: '189',
    yearsExperience: '18',
    hospital: 'San Raffaele Hospital',
    logoHospital: '/assets/hospitals/sanraffaelehospital.png',
    location: 'Milan, Italy',
    degreeObtained1: 'Doctor of Medicine (MD)',
    university1: 'University of Bologna',
    degreeObtained2: 'PhD in Cardiovascular Medicine',
    university2: 'University of Milan',
  },

  {
    id: 10,
    name: 'Lucas Müller',
    qualifications: 'MD, MPH',
    specialty: 'Dermatologist',
    languages: 'German, English',
    price: '79',
    yearsExperience: '14',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Berlin, Germany',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Humboldt University of Berlin',
    degreeObtained2: 'Master of Public Health',
    university2: 'Charité - Universitätsmedizin Berlin',
  },
  {
    id: 11,
    name: 'Maja Kowalska',
    qualifications: 'MD, MSc',
    specialty: 'Dermatologist',
    languages: 'Polish, English',
    price: '119',
    yearsExperience: '19',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Warsaw, Poland',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Medical University of Warsaw',
    degreeObtained2: 'Master of Science in Dermatology',
    university2: 'Jagiellonian University',
  },
  {
    id: 12,
    name: 'Sophie Leclerc',
    qualifications: 'MD, MBA',
    specialty: 'Dermatologist',
    languages: 'French, English',
    price: '89',
    yearsExperience: '11',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Brussels, Belgium',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Université Libre de Bruxelles',
    degreeObtained2:
      'Master of Business Administration in Healthcare Management',
    university2: 'Vlerick Business School',
  },
  {
    id: 13,
    name: 'Matteo Ferrari',
    qualifications: 'MD, PhD',
    specialty: 'Dietitian',
    languages: 'Italian, English',
    price: '179',
    yearsExperience: '28',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Rome, Italy',
    degreeObtained1: 'Master of Science in Nutrition',
    university1: 'University of Rome "La Sapienza"',
    degreeObtained2: 'Doctor of Philosophy in Food Science',
    university2: 'University of Bologna',
  },
  {
    id: 14,
    name: 'Maria Garcia',
    qualifications: 'MD, MSc',
    specialty: 'Dietitian',
    languages: 'Spanish, English',
    price: '149',
    yearsExperience: '16',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Madrid, Spain',
    degreeObtained1: 'Master in Clinical Nutrition and Dietetics',
    university1: 'Complutense University of Madrid',
    degreeObtained2: 'Doctor of Medicine',
    university2: 'Autonomous University of Madrid',
  },
  {
    id: 15,
    name: 'Irina Popescu',
    qualifications: 'MD, PhD',
    specialty: 'Dietitian',
    languages: 'Romanian, English',
    price: '119',
    yearsExperience: '18',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Bucharest, Romania',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Carol Davila University of Medicine and Pharmacy',
    degreeObtained2: 'Doctor of Philosophy in Food Science',
    university2:
      'University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca',
  },
  {
    id: 16,
    name: 'Henriette Jensen',
    qualifications: 'MD, MSc',
    specialty: 'Orthopedician',
    languages: 'Danish, English',
    price: '89',
    yearsExperience: '12',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Copenhagen, Denmark',
    degreeObtained1: 'Master of Science in Biomedical Engineering',
    university1: 'Technical University of Denmark',
    degreeObtained2: 'Doctor of Medicine',
    university2: 'University of Copenhagen',
  },

  {
    id: 17,
    name: 'Lucas Varga',
    qualifications: 'MD, PhD',
    specialty: 'Orthopedician',
    languages: 'Hungarian, German, English',
    price: '129',
    yearsExperience: '18',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Budapest, Hungary',
    degreeObtained1: 'Doctor of Medicine (MD), Semmelweis University',
    university1: 'Semmelweis University',
    degreeObtained2:
      'Doctor of Philosophy (PhD) in Orthopedic Surgery, University of Debrecen',
    university2: 'University of Debrecen',
  },
  {
    id: 18,
    name: 'Giulia Bianchi',
    qualifications: 'MD',
    specialty: 'Orthopedician',
    languages: 'Italian, English, Spanish',
    price: '79',
    yearsExperience: '22',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Rome, Italy',
    degreeObtained1: 'Doctor of Medicine (MD), Sapienza University of Rome',
    university1: 'Sapienza University of Rome',
    degreeObtained2: '',
    university2: '',
  },
  {
    id: 19,
    name: 'Mariusz Kowalski',
    qualifications: 'MD',
    specialty: 'Fertility Specialist',
    languages: 'Polish, English, Russian',
    price: '159',
    yearsExperience: '13',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Warsaw, Poland',
    degreeObtained1: 'Doctor of Medicine (MD), Medical University of Warsaw',
    university1: 'Medical University of Warsaw',
    degreeObtained2: '',
    university2: '',
  },
  {
    id: 20,
    name: 'Hanne Jorgensen',
    qualifications: 'MD',
    specialty: 'Fertility Specialist',
    languages: 'Danish, English, German',
    price: '89',
    yearsExperience: '15',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Copenhagen, Denmark',
    degreeObtained1: 'Doctor of Medicine (MD), University of Copenhagen',
    university1: 'University of Copenhagen',
    degreeObtained2: '',
    university2: '',
  },
  {
    id: 21,
    name: 'Andrei Popescu',
    qualifications: 'MD, PhD',
    specialty: 'Fertility Specialist',
    languages: 'Romanian, English, French',
    price: '179',
    yearsExperience: '21',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Bucharest, Romania',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Carol Davila University of Medicine and Pharmacy',
    degreeObtained2: 'Doctor of Philosophy (PhD)',
    university2: 'University of Medicine and Pharmacy Tîrgu Mureș',
  },
  {
    id: 22,
    name: 'Sophie Dubois',
    qualifications: 'MD',
    specialty: 'Cardiologist',
    languages: 'French, English, German',
    price: '99',
    yearsExperience: '14',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Paris, France',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Université Paris-Saclay',
    degreeObtained2: '',
    university2: '',
  },
  {
    id: 23,
    name: 'Tomasz Wozniak',
    qualifications: 'MD, PhD',
    specialty: 'Cardiologist',
    languages: 'Polish, English, Spanish',
    price: '149',
    yearsExperience: '20',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Krakow, Poland',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Jagiellonian University Medical College',
    degreeObtained2: 'Doctor of Philosophy (PhD)',
    university2: 'Medical University of Gdańsk',
  },
  {
    id: 24,
    name: 'Anna Andersson',
    qualifications: 'MD',
    specialty: 'Cardiologist',
    languages: 'Swedish, English, German',
    price: '69',
    yearsExperience: '11',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Stockholm, Sweden',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Karolinska Institutet',
    degreeObtained2: '',
    university2: '',
  },

  {
    id: 25,
    name: 'Lucie Dufour',
    qualifications: 'MD, DCH, MSc in Surgery, PhD in Medical Sciences',
    specialty: 'General Surgeon',
    languages: 'French, English, Spanish',
    price: '169',
    yearsExperience: '14',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Paris, France',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Université Paris-Saclay',
    degreeObtained2: 'Doctor of Philosophy in Medical Sciences',
    university2: 'Université Paris Descartes',
  },
  {
    id: 26,
    name: 'Karl Johansson',
    qualifications: 'MD, PhD, MSc in Surgery',
    specialty: 'General Surgeon',
    languages: 'Swedish, Finnish, English',
    price: '149',
    yearsExperience: '18',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Helsinki, Finland',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'University of Helsinki',
    degreeObtained2: 'Doctor of Philosophy in Medical Sciences',
    university2: 'University of Turku',
  },
  {
    id: 27,
    name: 'Maria Silva',
    qualifications: 'MD, DCH, PhD in Medicine',
    specialty: 'General Surgeon',
    languages: 'Portuguese, English, German',
    price: '179',
    yearsExperience: '11',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Lisbon, Portugal',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'University of Lisbon',
    degreeObtained2: 'Doctor of Philosophy in Medicine',
    university2: 'University of Porto',
  },
  {
    id: 28,
    name: 'Janis Petrov',
    qualifications: 'MD, DCH, PhD in Gastroenterology',
    specialty: 'Gastroenterologist',
    languages: 'Latvian, Russian, English',
    price: '129',
    yearsExperience: '22',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Riga, Latvia',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'University of Latvia',
    degreeObtained2: 'Doctor of Philosophy in Gastroenterology',
    university2: 'Rīga Stradiņš University',
  },
  {
    id: 29,
    name: 'Elena Petrova',
    qualifications: 'MD, DCH, PhD',
    specialty: 'Gastroenterologist',
    languages: 'Bulgarian, Russian, English',
    price: '179',
    yearsExperience: '15',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Sofia, Bulgaria',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Medical University of Sofia',
    degreeObtained2: 'Doctor of Philosophy in Gastroenterology',
    university2: 'University of Edinburgh',
  },
  {
    id: 30,
    name: 'Miguel Gonzalez',
    qualifications: 'MD, DCH, MSc',
    specialty: 'Gastroenterologist',
    languages: 'Spanish, Catalan, English',
    price: '99',
    yearsExperience: '12',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Barcelona, Spain',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'University of Barcelona',
    degreeObtained2: 'Master of Science in Gastroenterology',
    university2: 'Universitat Autònoma de Barcelona',
  },

  {
    id: 37,
    name: 'Maria Schmidt',
    qualifications: 'MD, MSc',
    specialty: 'Cardiologist',
    languages: 'German, English',
    price: '179',
    yearsExperience: '15',
    hospital: 'Vienna General Hospital',
    logoHospital: '/assets/hospitals/viennageneralhospital.png',
    location: 'Vienna, Austria',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Medical University of Vienna',
    degreeObtained2: 'Master of Science in Cardiology',
    university2: 'University of Salzburg',
  },

  {
    id: 32,
    name: 'Erik Andersen',
    qualifications: 'MD, PhD',
    specialty: 'Pulmonologist',
    languages: 'Danish, English, German',
    price: '179',
    yearsExperience: '16',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Copenhagen, Denmark',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'University of Copenhagen',
    degreeObtained2: 'Doctor of Philosophy in Pulmonology',
    university2: 'Imperial College London',
  },
  {
    id: 37,
    name: 'Erik Johansen',
    qualifications: 'MD, PhD',
    specialty: 'Cardiologist',
    languages: 'Norwegian, English',
    price: '199',
    yearsExperience: '20',
    hospital: 'Oslo University Hospital',
    logoHospital: '/assets/hospitals/oslo_university_hospital.png',
    location: 'Oslo, Norway',
    degreeObtained1: 'Bachelor of Medicine',
    university1: 'University of Oslo',
    degreeObtained2: 'Doctor of Medicine',
    university2: 'University of Bergen',
  },
  {
    id: 34,
    name: 'Luisa Rodriguez',
    qualifications: 'MD, MSc',
    specialty: 'Oncologist',
    languages: 'Spanish, English',
    price: '179',
    yearsExperience: '17',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Madrid, Spain',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'Complutense University of Madrid',
    degreeObtained2: 'Master of Science',
    university2: 'Autonomous University of Madrid',
  },
  {
    id: 35,
    name: 'Lars Andersen',
    qualifications: 'MD, PhD',
    specialty: 'Oncologist',
    languages: 'Danish, German',
    price: '189',
    yearsExperience: '14',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'Copenhagen, Denmark',
    degreeObtained1: 'Doctor of Medicine',
    university1: 'University of Copenhagen',
    degreeObtained2: 'Doctor of Philosophy',
    university2: 'Technical University of Denmark',
  },

  {
    id: 36,
    name: 'Sophie Smith',
    doctorImage: '/assets/doctors/pexels-tima-miroshnichenko-5452201.jpg',
    qualifications: 'MD, PhD',
    specialty: 'Pediatrician',
    languages: 'English, French',
    price: '149',
    yearsExperience: '18',
    hospital: 'myDoc Hospitals',
    logoHospital: '/assets/hospitals/myDoc.png',
    location: 'London, England',
    degreeObtained1: 'MBBS',
    university1: 'Imperial College London',
    degreeObtained2: 'MSc in Child Health',
    university2: 'University College London',
  },
];
